### ISSUE TITLE
Create a GitHub team for Access to the `adventure` repo

### ISSUE THREAD

**Issue by ecarlste** [RhiannaDains/adventure#1]
Check out these docs to allow you to create a team within your organization.
[Creating a Team](https://docs.github.com/en/organizations/organizing-members-into-teams/creating-a-team)

Once you have the team created, you'll need to add that team to this repository and add me and any others you want to have access as contributors (via pull requests) to the team. You'll also need to set the roles for the team on the repository. 

The [managing teams on your repo](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-teams-and-people-with-access-to-your-repository) docs might help with this.
Let me know if you need any help with this.

- [x] Create team
- [x] Add members to team
- [x] Move repo to new organization created for the team
- [x] Ask for Erik's help

**Comment by ecarlste** [comment]
@RhiannaDains just wanted to ping you so that you had visibility into the fact that I created this issue to help you track things we need to potentially do on the adventure game :-)

**Comment by ecarlste** [comment]
@RhiannaDains I updated the ToDo list here on the issue so that the progress made is synced. We still need to move the repo over to the organization.

Here's a link that shows in a few paragraphs with diagrams how to do so.

https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account

**Comment by RhiannaDains** [comment]
@ecarlste Done!
